### ISSUE TITLE
Typos in /documentation

### ISSUE THREAD

**Issue by techtolentino** [getpavilion/getpavilion.github.io#3]
(First of all, let me say - very nice work! I really think you've created something awesome - the docs look great too, btw)

**Columns & breakpoints**
- [x] 'width's' should be 'widths'
- [x] 'When a column breaks out of it's breakpoint' should be 'When a column breaks out of **its** breakpoint' 

**Columns**
- [x] 'Altough' should be 'Although'
- [x] 'exeption' should be 'exception'

**Using EM & REM**

- [x] 'The EM unit inherits it's value...' should be 'The EM unit inherits **its** value...'
- [x] 'troughout' should be 'throughout'

**Forms**
- [x] 'radiobuttons', (I'm guessing) should be 'radio buttons'

**Typography**
- [x] 'parapgraph' should be 'paragraph'

**Support**
- [x] 'Altough' should be 'Although'

This is all that I could find - but again, very nice work!!

**Comment by getpavilion** [comment]
Thanks you so much for check all this! I've fixed all you findings. 

And good to hear you like it :) Thanks again!

**Comment by techtolentino** [comment]
Ah, I forgot one!

**Flexbox**
'Ofcourse there are numerous other' should be 'Of course there are numerous'

**Comment by getpavilion** [comment]
Done! Thanks!
